/* App.svelte generated by Svelte v3.50.1 */
import { create_ssr_component } from "svelte/internal";

const App = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<html lang="${"en"}"><head><!DOCTYPE html>
<meta name="${"keywords"}" content="${"theban, the-ban, ban, banano, news, insights, events, curiosities, lifestyle"}">
<meta name="${"description"}" content="${"Get the latest Banano news, insights, events curiosities and lifestyle from The Ban"}">
<meta name="${"author"}" content="${"Prussia & SizzlingPotassium642"}">
<meta name="${"robots"}" content="${""}">
<meta charset="${"ISO-8859-1"}"> 
<meta charset="${"UTF-8"}"> 
<title>The Ban</title>
<style>.TOPBAR {
font-family:"Franklin Gothic Medium";

  width: 100%;
  height: auto;
  background-color: #FFFFFF;
  position: fixed;
  top: -18px;
  left: 0px;
  box-shadow: 0px 0px 3vw #000000;
}

	.TOPBARLINK {
	  height:96px;
	  color: #4CBF4A;
	  background-color:#FFFFFF;
	  font-size: 0.9vw;
	  		  font-weight:bold;

	  border-width: 0.3vw;
	  border-style:inherit;
	  border-color:#4CBF4A;
    text-decoration: none;
    vertical-align:top;
	
	}
	
	.TOPBARLINK:hover {
		  background-color:#4CBF4A;
		  font-weight:bold;
        color: #FFFFFF;
        border-color: #FFFFFF;
        text-shadow: 0px 0px 0.0vw #FFFFFF;
		        border-bottom: 0.4vw solid #FFFFFF;
				border-top: 0.4vw solid #FFFFFF;

      }

.BOTTOMBAR {
	height: 9px;
  width: 100%;
  background-color: #4CBF4A;
  position: ;
  bottom: 0px;
  right: 0px
}

.PAGE {
font-family:"Franklin Gothic Medium";
	}
	
.GREEN {
	background-color: #4CBF4A;
	}
	
.WHITE {
	background-color: #FFFFFF;
	}
a {
	font-family: Franklin Gothic Medium;
}
body,td,th {
	font-family: Franklin Gothic Medium;
}
.hrw {
        display: block;
        height: 0.1vw;
        border: 0;
        border-top: 0.1vw solid #ffffff;
        margin: 1em 0;
        padding: 0;
        width: 80%;
      }
.style4 {color: #FFFFFF;
font-size: 0.8vw;}
.style4BIG {color: #FFFFFF;
font-size: 1.2vw;}
.style5 {color: #4CBF4A;
font-size: 0.8vw;}
.style5BIG {color: #4CBF4A;
font-size: 1.2vw;}

.style6 {color: #4CBF4A; font-weight: bold; }
.style7 {color: #FFFFFF; font-weight: bold; }



.BUTTONONGREENVERTICALBORDER {
width:100%;
	font-size: 1vw;
	color: #FFFFFF;
  background-color: transparent;
  border-style:solid;
  border-color: transparent;
  border-width: 0.2vw;
  width: auto;
  height: auto;
  vertical-align:middle;
  align: center;
  border-radius: 0.0vw/0.0vw;
}

.BUTTONONGREENVERTICALBORDER:hover {
width:100%;
text-transform:uppercase;
  border-width: 0.2vw;
        color: #4CBF4A;
	    border-left: 0.2vw solid #FFFFFF;
		border-right: 0.2vw solid #FFFFFF;
        text-shadow: 0vw 0vw 0.0vw #FFFFFF;
      }



.BUTTONONGREENHORIZONTALBORDER {
width:100%;
	font-size: 1vw;
	color: #FFFFFF;
  background-color: transparent;
  border-style:solid;
  border-color: transparent;
  border-width: 0.2vw;
  width: auto;
  height: auto;
  vertical-align:middle;
  align: center;
  border-radius: 0.0vw/0.0vw;
}

.BUTTONONGREENHORIZONTALBORDER:hover {
width:100%;
text-transform:uppercase;
  border-width: 0.2vw;
        color: #4CBF4A;
	    border-top: 0.2vw solid #FFFFFF;
		border-bottom: 0.2vw solid #FFFFFF;
        text-shadow: 0vw 0vw 0.0vw #FFFFFF;
      }




.BUTTONONWHITEVERTICALBORDER {
width:100%;
	font-size: 1vw;
	color: #FFFFFF;
  background-color: transparent;
  border-style:solid;
  border-color: transparent;
  border-width: 0.2vw;
  width: auto;
  height: auto;
  vertical-align:middle;
  align: center;
  border-radius: 0.0vw/0.0vw;
}

.BUTTONONWHITEVERTICALBORDER:hover {
width:100%;
text-transform:uppercase;
  border-width: 0.2vw;
        color: #4CBF4A;
	    border-left: 0.2vw solid #4CBF4A;
		border-right: 0.2vw solid #4CBF4A;
        text-shadow: 0vw 0vw 0.0vw #4CBF4A;
      }



.BUTTONONWHITEHORIZONTALBORDER {
width:100%;
	font-size: 1vw;
  font-weight: bold;
  background-color: transparent;
  border-style:solid;
  border-color: transparent;
  border-width: 0.2vw;
  width: auto;
  height: auto;
  vertical-align:middle;
  align: center;
  border-radius: 0.0vw/0.0vw;
}

.BUTTONONWHITEHORIZONTALBORDER:hover {
width:100%;

text-transform:uppercase;
  border-width: 0.2vw;
        color: #4CBF4A;
	    border-top: 0.2vw solid #4CBF4A;
		border-bottom: 0.2vw solid #4CBF4A;
        text-shadow: 0vw 0vw 0.0vw #4CBF4A;
      }

body {
	background-color: #4CBF4A;
}


.BANADWHITE {
	color: #4CBF4A;
  background-color: rgba(255,255,255,0.02);
    border-color: transparent;
  border-style:dashed;
  border-width: 0.01vw;
  width: 100%;
  height: 100%;
  vertical-align:middle;
  align: center;
  border-radius: 0.1vw/0.1vw;
}

.BANADWHITE:hover {
  border-width: 0.1vw;
        color: #4CBF4A;
        border-color: #4CBF4A;
        text-shadow: 0px 0px 0.1vw #4CBF4A;
		        background-color: rgba(76,191,75,0.3);
		  border-style:dashed;

      }


.BANADGREEN {
	color: #FFFFFF;
  background-color: rgba(255,255,255,0.02);
  border-color: transparent;
  border-width: 0.01vw;
  border-style:dashed;
  width: 100%;
  height: 100%;
  vertical-align:middle;
  align: center;
  border-radius: 0.1vw/0.1vw;
}

.BANADGREEN:hover {
  border-width: 0.1vw;
        color: #FFFFFF;
        border-color: #FFFFFF;
        text-shadow: 0px 0px 0.1vw #FFFFFF;
        background-color: rgba(255,255,255,0.3);
		  border-style:dashed;

      }

</style>
<meta http-equiv="${"Content-Type"}" content="${"text/html; charset=iso-8859-1"}"></head>


<body><p class="${"PAGE"}">
</p><table width="${"60%%"}" border="${"0"}" align="${"center"}" cellpadding="${"0"}" cellspacing="${"0"}"><tr><td width="${"20%"}"><div align="${"center"}"><img src="${"img/theban.jpg"}" alt="${"The Ban"}" width="${"55%"}"></div></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td></tr></table>




<p class="${"GREEN"}"></p><table width="${"100%"}" border="${"0"}" align="${"center"}" cellpadding="${"5"}" cellspacing="${"5"}" bgcolor="${"#4CBF4A"}"><tr><td width="${"20%"}" rowspan="${"3"}"><table width="${"100%%"}" border="${"0"}" cellpadding="${"5"}" cellspacing="${"5"}" class="${"style4"}"><tr><td class="${"style4"}"><button class="${"BANADGREEN"}"><p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">(Banano-Ad)</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p></button></td>
        <td width="${"40%"}"> </td></tr></table></td>
    <td colspan="${"2"}" rowspan="${"3"}"><button class="${"BUTTONONGREENVERTICALBORDER"}" style="${"width:100%"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td><img src="${"https://cdn.pixabay.com/photo/2016/08/30/15/27/rolls-royce-1631074_960_720.jpg"}" alt="${"The World's Most Luxurious Banana"}" width="${"100%"}"></td></tr>
      <tr><td><h1 class="${"style4BIG"}">The World&#39;s Most Luxurious Banana</h1>
          <span class="${"style4BIG"}"><br>
          <em>by Banano Fam </em></span></td></tr></table></button></td>
    <td width="${"20%"}"><button class="${"BUTTONONGREENHORIZONTALBORDER"}" style="${"width:100%"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td width="${"60%"}"><img src="${"https://get.pxhere.com/photo/meal-food-produce-small-fresh-rack-breakfast-baking-dessert-delicious-homemade-bread-loaf-baked-three-loaves-ciabatta-cooling-individual-baked-goods-beer-bread-grass-family-pumpkin-bread-banana-bread-soda-bread-758773.jpg"}" alt="${"Air-fried Banana Bread"}" width="${"100%"}"></td>
        <td><h3 class="${"style4"}">Air-fried Banana Bread</h3>
          <span class="${"style4"}"><br>
            <em>by Banano Fam</em></span><em></em></td></tr></table></button></td>
    <td width="${"20%"}" rowspan="${"3"}"><table width="${"100%%"}" border="${"0"}" cellpadding="${"5"}" cellspacing="${"5"}" class="${"style4"}"><tr><td width="${"40%"}" class="${"style4"}"><p class="${"style5"}"> </p></td>
        <td><button class="${"BANADGREEN"}"><p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
	      <p align="${"center"}" class="${"style4"}">|</p>
	      <p align="${"center"}" class="${"style4"}">|</p>
		  		  <p align="${"center"}" class="${"style4"}">|</p>
	      <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">(Banano-Ad)</p>
          <p align="${"center"}" class="${"style4"}">|</p>
		  		  <p align="${"center"}" class="${"style4"}">|</p>
	      <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
		  <p align="${"center"}" class="${"style4"}">|</p>
	      <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p></button></td></tr></table></td></tr>
  <tr><td width="${"20%"}"><button class="${"BUTTONONGREENHORIZONTALBORDER"}" style="${"width:100%"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td width="${"60%"}"><img src="${"https://images.pexels.com/photos/2872747/pexels-photo-2872747.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"}" alt="${"Major Effects Bananas Have on Your Health"}" width="${"100%"}"></td>
        <td><h3 class="${"style4"}">Major Effects Bananas Have on Your Health</h3>
          <span class="${"style4"}"><br>
            <em>by Banano Fam</em></span><em></em></td></tr></table></button></td></tr>
  <tr><td width="${"20%"}"><button class="${"BUTTONONGREENHORIZONTALBORDER"}" style="${"width:100%"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td width="${"60%"}"><img src="${"https://c4.wallpaperflare.com/wallpaper/796/112/999/evolution-simple-che-guevara-white-background-wallpaper-preview.jpg"}" alt="${"Short History of Banana"}" width="${"100%"}"></td>
        <td><h3 class="${"style4"}">Short History of Banana</h3>
          <span class="${"style4"}"><br>
            <em>by Banano Fam </em></span></td></tr></table></button></td></tr></table>

<p class="${"WHITE"}"></p><table width="${"100%"}" border="${"0"}" align="${"center"}" cellpadding="${"5"}" cellspacing="${"5"}" bgcolor="${"#FFFFFF"}"><tr><td width="${"20%"}" rowspan="${"3"}"><table width="${"100%%"}" border="${"0"}" cellpadding="${"5"}" cellspacing="${"5"}" class="${"style5"}"><tr><td class="${"style4"}"><button class="${"BANADWHITE"}"><p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">(Banano-Ad)</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p></button></td>
        <td width="${"40%"}"> </td></tr></table></td>
    <td colspan="${"3"}"><div style="${"width:100%"}" align="${"center"}"><button class="${"BUTTONONWHITEHORIZONTALBORDER"}" style="${"width:100%"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td width="${"100%"}"><img src="${"https://static.wixstatic.com/media/47f9f4_07dcc207d99c4e0f9d1b390b71a0b516~mv2.png/v1/fill/w_740,h_551,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/47f9f4_07dcc207d99c4e0f9d1b390b71a0b516~mv2.png"}" alt="${"Banano Hackathon Competition aka BOOSTER 2 "}" width="${"100%"}"></td></tr>
  <tr><td width="${"100%"}"><h1 class="${"style5BIG"}">Banano Hackathon Competition aka BOOSTER 2 </h1>
      <p class="${"style5BIG"}"><br>
    <em>by Banano Fam </em></p></td></tr></table></button></div></td>
    <td width="${"20%"}" rowspan="${"3"}"><table width="${"100%%"}" border="${"0"}" cellpadding="${"5"}" cellspacing="${"5"}" class="${"style5"}"><tr><td width="${"40%"}" class="${"style4"}"><p class="${"style5"}"> </p></td>
        <td><button class="${"BANADWHITE"}"><p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">(Banano-Ad)</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p></button></td></tr></table></td></tr>
  <tr></tr>
  <tr><td width="${"20%"}"><button class="${"BUTTONONWHITEVERTICALBORDER"}" style="${"width:100%"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td><div align="${"center"}"><img src="${"https://static.wixstatic.com/media/b714c2_5735e38f1d1e4b228787cdfdf486b288~mv2.png/v1/fill/w_412,h_365,fp_0.50_0.50,q_90,enc_auto/b714c2_5735e38f1d1e4b228787cdfdf486b288~mv2.webp"}" alt="${"Monkey Web Coding Challenge"}" width="${"100%"}"></div></td></tr>
      <tr><td><h3 class="${"style5"}">Monkey Web Coding Challenge #1</h3>
          <span class="${"style5"}"><br>
          <em>by Banano Fam</em></span></td></tr></table></button></td>
    <td width="${"20%"}"><button class="${"BUTTONONWHITEVERTICALBORDER"}" style="${"width:100%"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td><div align="${"center"}"><img src="${"https://static.wixstatic.com/media/b714c2_5735e38f1d1e4b228787cdfdf486b288~mv2.png/v1/fill/w_412,h_365,fp_0.50_0.50,q_90,enc_auto/b714c2_5735e38f1d1e4b228787cdfdf486b288~mv2.webp"}" alt="${"Monkey Web Coding Challenge"}" width="${"100%"}"></div></td></tr>
      <tr><td><h3 class="${"style5"}">Monkey Web Coding Challenge #2</h3>
          <span class="${"style5"}"><br>
          <em>by Banano Fam</em></span></td></tr></table></button></td>
    <td width="${"20%"}"><button class="${"BUTTONONWHITEVERTICALBORDER"}" style="${"width:100%"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td><div align="${"center"}"><img src="${"https://static.wixstatic.com/media/b714c2_5735e38f1d1e4b228787cdfdf486b288~mv2.png/v1/fill/w_412,h_365,fp_0.50_0.50,q_90,enc_auto/b714c2_5735e38f1d1e4b228787cdfdf486b288~mv2.webp"}" alt="${"Monkey Web Coding Challenge"}" width="${"100%"}"></div></td></tr>
      <tr><td><h3 class="${"style5"}">Monkey Web Coding Challenge #3</h3>
          <span class="${"style5"}"><br>
          <em>by Banano Fam</em></span></td></tr></table></button></td></tr></table>

<p class="${"GREEN"}"></p><table width="${"100%"}" border="${"0"}" align="${"center"}" cellpadding="${"5"}" cellspacing="${"5"}" bgcolor="${"#4CBF4A"}"><tr><td width="${"20%"}" rowspan="${"3"}"><table width="${"100%%"}" border="${"0"}" cellpadding="${"5"}" cellspacing="${"5"}" class="${"style4"}"><tr><td class="${"style4"}"><button class="${"BANADGREEN"}"><p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">(Banano-Ad)</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p></button></td>
        <td width="${"40%"}"> </td></tr></table></td>
    <td colspan="${"2"}" rowspan="${"3"}"><button class="${"BUTTONONGREENVERTICALBORDER"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td><img src="${"https://static.wixstatic.com/media/1aa9b8_a85e4bcc4b424ee3b557c44254862778~mv2.png/v1/fill/w_740,h_491,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/1aa9b8_a85e4bcc4b424ee3b557c44254862778~mv2.png"}" alt="${"Emmys 2022"}" width="${"100%"}"></td></tr>
      <tr><td><h1 class="${"style4BIG"}">Emmys 2022 </h1>
          <span class="${"style4BIG"}"><br>
          <em>by Banano Fam </em></span></td></tr></table></button></td>
    <td width="${"20%"}"><button class="${"BUTTONONGREENHORIZONTALBORDER"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td width="${"60%"}"><img src="${"https://static.wixstatic.com/media/299fa9_6352b91c38df437c87ad4ef3cc1415db~mv2.png/v1/fill/w_740,h_417,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/299fa9_6352b91c38df437c87ad4ef3cc1415db~mv2.png"}" alt="${"Sunday Community Call"}" width="${"100%"}"></td>
        <td><h3 class="${"style4"}">Sunday Community Call 1</h3>
          <span class="${"style4"}"><br>
            <em>by Banano Fam </em></span></td></tr></table></button></td>
    <td width="${"20%"}" rowspan="${"3"}"><table width="${"100%%"}" border="${"0"}" cellpadding="${"5"}" cellspacing="${"5"}" class="${"style4"}"><tr><td width="${"40%"}" class="${"style4"}"><p class="${"style5"}"> </p></td>
        <td><button class="${"BANADGREEN"}"><p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">(Banano-Ad)</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p>
          <p align="${"center"}" class="${"style4"}">|</p></button></td></tr></table></td></tr>
  <tr><td width="${"20%"}"><button class="${"BUTTONONGREENHORIZONTALBORDER"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td width="${"60%"}"><img src="${"https://static.wixstatic.com/media/299fa9_6352b91c38df437c87ad4ef3cc1415db~mv2.png/v1/fill/w_740,h_417,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/299fa9_6352b91c38df437c87ad4ef3cc1415db~mv2.png"}" alt="${"Sunday Community Call"}" width="${"100%"}"></td>
        <td><h3 class="${"style4"}">Sunday Community Call 2</h3>
          <span class="${"style4"}"><br>
            <em>by Banano Fam </em></span></td></tr></table></button></td></tr>
  <tr><td width="${"20%"}"><button class="${"BUTTONONGREENHORIZONTALBORDER"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td width="${"60%"}"><img src="${"https://static.wixstatic.com/media/299fa9_6352b91c38df437c87ad4ef3cc1415db~mv2.png/v1/fill/w_740,h_417,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/299fa9_6352b91c38df437c87ad4ef3cc1415db~mv2.png"}" alt="${"Sunday Community Call"}" width="${"100%"}"></td>
        <td><h3 class="${"style4"}">Sunday Community Call 3</h3>
          <span class="${"style4"}"><br>
            <em>by Banano Fam </em></span></td></tr></table></button></td></tr></table>

<p class="${"WHITE"}"></p><table width="${"100%"}" border="${"0"}" align="${"center"}" cellpadding="${"5"}" cellspacing="${"5"}" bgcolor="${"#FFFFFF"}"><tr><td width="${"20%"}" rowspan="${"3"}"><table width="${"100%%"}" border="${"0"}" cellpadding="${"5"}" cellspacing="${"5"}" class="${"style5"}"><tr><td class="${"style4"}"><button class="${"BANADWHITE"}"><p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">(Banano-Ad)</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p></button></td>
        <td width="${"40%"}"> </td></tr></table></td>
    <td colspan="${"3"}"><div style="${"width:100%"}" align="${"center"}"><button class="${"BUTTONONWHITEHORIZONTALBORDER"}" style="${"width:100%"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td width="${"100%"}"><img src="${"https://static.wixstatic.com/media/47f9f4_07dcc207d99c4e0f9d1b390b71a0b516~mv2.png/v1/fill/w_740,h_551,al_c,q_90,usm_0.66_1.00_0.01,enc_auto/47f9f4_07dcc207d99c4e0f9d1b390b71a0b516~mv2.png"}" alt="${"Banano Hackathon Competition aka BOOSTER 2 "}" width="${"100%"}"></td></tr>
  <tr><td width="${"100%"}"><h1 class="${"style5BIG"}">Banano Hackathon Competition aka BOOSTER 2 </h1>
      <p class="${"style5BIG"}"><br>
    <em>by Banano Fam </em></p></td></tr></table></button></div></td>
    <td width="${"20%"}" rowspan="${"3"}"><table width="${"100%%"}" border="${"0"}" cellpadding="${"5"}" cellspacing="${"5"}" class="${"style5"}"><tr><td width="${"40%"}" class="${"style4"}"><p class="${"style5"}"> </p></td>
        <td><button class="${"BANADWHITE"}"><p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">(Banano-Ad)</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p>
          <p align="${"center"}" class="${"style5"}">|</p></button></td></tr></table></td></tr>
  <tr></tr>
  <tr><td width="${"20%"}"><button class="${"BUTTONONWHITEVERTICALBORDER"}" style="${"width:100%"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td><div align="${"center"}"><img src="${"https://static.wixstatic.com/media/b714c2_5735e38f1d1e4b228787cdfdf486b288~mv2.png/v1/fill/w_412,h_365,fp_0.50_0.50,q_90,enc_auto/b714c2_5735e38f1d1e4b228787cdfdf486b288~mv2.webp"}" alt="${"Monkey Web Coding Challenge"}" width="${"100%"}"></div></td></tr>
      <tr><td><h3 class="${"style5"}">Monkey Web Coding Challenge #1</h3>
          <span class="${"style5"}"><br>
          <em>by Banano Fam</em></span></td></tr></table></button></td>
    <td width="${"20%"}"><button class="${"BUTTONONWHITEVERTICALBORDER"}" style="${"width:100%"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td><div align="${"center"}"><img src="${"https://static.wixstatic.com/media/b714c2_5735e38f1d1e4b228787cdfdf486b288~mv2.png/v1/fill/w_412,h_365,fp_0.50_0.50,q_90,enc_auto/b714c2_5735e38f1d1e4b228787cdfdf486b288~mv2.webp"}" alt="${"Monkey Web Coding Challenge"}" width="${"100%"}"></div></td></tr>
      <tr><td><h3 class="${"style5"}">Monkey Web Coding Challenge #2</h3>
          <span class="${"style5"}"><br>
          <em>by Banano Fam</em></span></td></tr></table></button></td>
    <td width="${"20%"}"><button class="${"BUTTONONWHITEVERTICALBORDER"}" style="${"width:100%"}"><p></p><table width="${"100%%"}" border="${"0"}" cellspacing="${"5"}" cellpadding="${"5"}"><tr><td><div align="${"center"}"><img src="${"https://static.wixstatic.com/media/b714c2_5735e38f1d1e4b228787cdfdf486b288~mv2.png/v1/fill/w_412,h_365,fp_0.50_0.50,q_90,enc_auto/b714c2_5735e38f1d1e4b228787cdfdf486b288~mv2.webp"}" alt="${"Monkey Web Coding Challenge"}" width="${"100%"}"></div></td></tr>
      <tr><td><h3 class="${"style5"}">Monkey Web Coding Challenge #3</h3>
          <span class="${"style5"}"><br>
          <em>by Banano Fam</em></span></td></tr></table></button></td></tr></table>




<p align="${"center"}" class="${"TOPBAR"}"></p><table width="${"60%%"}" border="${"0"}" align="${"center"}" cellpadding="${"0"}" cellspacing="${"0"}"><tr><td width="${"20%"}"><div align="${"center"}"><img src="${"img/theban.jpg"}" alt="${"The Ban"}" width="${"75%"}"></div></td>
    <td><div align="${"center"}" class="${"style6"}"><button class="${"TOPBARLINK"}">NEWS</button></div></td>
    <td><div align="${"center"}" class="${"style6"}"><button class="${"TOPBARLINK"}">INSIGHTS</button></div></td>
    <td><div align="${"center"}" class="${"style6"}"><button class="${"TOPBARLINK"}">EVENTS</button></div></td>
    <td><div align="${"center"}" class="${"style6"}"><button class="${"TOPBARLINK"}">CURIOSITIES</button></div></td>
    <td><div align="${"center"}" class="${"style6"}"><button class="${"TOPBARLINK"}">LIFESTYLE</button></div></td></tr></table>


<p align="${"center"}" class="${"BOTTOMBAR"}"></p><table width="${"100%"}" border="${"0"}" align="${"center"}" cellpadding="${"5"}" cellspacing="${"5"}" bgcolor="${"#4CBF4A"}"><tr><td width="${"20%"}" valign="${"middle"}"><div align="${"center"}"></div></td>
    <td width="${"20%"}" valign="${"middle"}"><p align="${"center"}" class="${"style7"}">FOLLOW THE BAN
    </p><div align="${"center"}"><hr align="${"center"}" class="${"hrw"}"></div>
	<table width="${"100%%"}" border="${"0"}" align="${"center"}" cellpadding="${"5"}" cellspacing="${"5"}" class="${"style4"}"><tr><td width="${"44%"}"><div align="${"right"}">(logo-link)</div></td>
    <td width="${"56%"}"><div align="${"left"}">(social-name-link)</div></td></tr>
  <tr><td width="${"44%"}"><div align="${"right"}">(logo-link)</div></td>
    <td width="${"56%"}"><div align="${"left"}">(social-name-link)</div></td></tr>
  <tr><td width="${"44%"}"><div align="${"right"}">(logo-link)</div></td>
    <td width="${"56%"}"><div align="${"left"}">(social-name-link)</div></td></tr>
  <tr><td width="${"44%"}"><div align="${"right"}">(logo-link)</div></td>
    <td width="${"56%"}"><div align="${"left"}">(social-name-link)</div></td></tr></table></td>
    <td width="${"40%"}" valign="${"middle"}"><p align="${"center"}" class="${"style7"}">SERVICES
    </p><div align="${"center"}"><hr align="${"center"}" class="${"hrw"}"></div>
      <table width="${"100%%"}" border="${"0"}" align="${"center"}" cellpadding="${"5"}" cellspacing="${"5"}" class="${"style4"}"><tr><td width="${"50%"}" class="${"style4"}"><div align="${"center"}">(other-the-ban-page-link)</div></td>
          <td width="${"50%"}" class="${"style4"}"><div align="${"center"}">(other-the-ban-page-link)</div></td></tr>
        <tr><td width="${"50%"}" class="${"style4"}"><div align="${"center"}">(other-the-ban-page-link)</div></td>
          <td width="${"50%"}" class="${"style4"}"><div align="${"center"}">(other-the-ban-page-link)</div></td></tr>
        <tr><td colspan="${"2"}" class="${"style4"}"><div align="${"center"}">(disclaimer-additional-info)<br>
              +<br>
              (rights-and-signature)</div></td></tr></table></td>
    <td width="${"20%"}" valign="${"middle"}"><div align="${"center"}"></div></td></tr></table>
<table width="${"100%"}" border="${"0"}" align="${"center"}" cellpadding="${"5"}" cellspacing="${"5"}" bgcolor="${"#4CBF4A"}"><tr><td valign="${"middle"}"><div align="${"center"}"></div>
      <p align="${"center"}" class="${"style7"}">SPONSORED BY </p><div align="${"center"}"><hr align="${"center"}" class="${"hrw"}"></div>         <p align="${"center"}" class="${"style7"}"></p>    <div align="${"center"}"></div></td></tr>
  <tr><td valign="${"middle"}" class="${"style4"}"><div align="${"center"}" class="${"style4"}">(sponsor-silhouette-logo-white) (sponsor-silhouette-logo-white) (sponsor-silhouette-logo-white) (sponsor-silhouette-logo-white) (sponsor-silhouette-logo-white) (sponsor-silhouette-logo-white)  </div></td></tr></table></body></html>`;
});

export default App;